In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv("tmdb_5000_movies.csv")
credits = pd.read_csv("tmdb_5000_credits.csv")

In [3]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [4]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [5]:
movies.merge(credits, on='title')

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4804,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]",...,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,9367,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],...,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,72766,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...",...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6,231617,"[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,126186,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...",...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16,25975,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [6]:
movies=movies.merge(credits, on='title')

In [7]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [8]:
# genres
# id
# keywords
# title
# overview
# cast
# crew
movies=movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [9]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [10]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [11]:
movies.dropna(inplace=True)

In [12]:
movies.duplicated().sum()

0

In [13]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [14]:
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [15]:
# generate the list or convert dict. into list
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [16]:
movies['genres']=movies['genres'].apply(convert)

In [17]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [18]:
movies['keywords']=movies['keywords'].apply(convert)

In [19]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [20]:
def convert3(obj):
    L=[]
    counter=0
    for i in ast.literal_eval(obj):
        if counter!=3:
            L.append(i['name'])
            counter+=1
        else:
            break
    return L

In [21]:
movies['cast']=movies['cast'].apply(convert)

In [22]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [23]:
def fetch_director(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            L.append(i['name'])
            break
    return L

In [24]:
movies['crew']=movies['crew'].apply(convert)

In [25]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[Stephen E. Rivkin, Rick Carter, Christopher B..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[Dariusz Wolski, Gore Verbinski, Jerry Bruckhe..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[Thomas Newman, Sam Mendes, Anna Pinnock, John..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[Hans Zimmer, Charles Roven, Christopher Nolan..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[Andrew Stanton, Andrew Stanton, John Lasseter..."

In [26]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [27]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[Stephen E. Rivkin, Rick Carter, Christopher B..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[Dariusz Wolski, Gore Verbinski, Jerry Bruckhe..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[Thomas Newman, Sam Mendes, Anna Pinnock, John..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[Hans Zimmer, Charles Roven, Christopher Nolan..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[Andrew Stanton, Andrew Stanton, John Lasseter..."

In [28]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","")for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","")for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","")for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","")for i in x])

In [29]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...","[StephenE.Rivkin, RickCarter, ChristopherBoyes..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...","[DariuszWolski, GoreVerbinski, JerryBruckheime..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...","[ThomasNewman, SamMendes, AnnaPinnock, JohnLog..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...","[HansZimmer, CharlesRoven, ChristopherNolan, C..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...","[AndrewStanton, AndrewStanton, JohnLasseter, C..."

In [30]:
movies['tags']=movies['overview']+movies['genres']+movies['cast']+movies['crew']+movies['keywords']

In [31]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...","[StephenE.Rivkin, RickCarter, ChristopherBoyes...","[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...","[DariuszWolski, GoreVerbinski, JerryBruckheime...","[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...","[ThomasNewman, SamMendes, AnnaPinnock, JohnLog...","[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...","[HansZimmer, CharlesRoven, ChristopherNolan, C...","[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...","[AndrewStanton, AndrewStanton, JohnLasseter, C...","[John, Carter, is, a, war-weary,, former, mili..."

In [32]:
new_df=movies[['movie_id','title','tags']]

In [33]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [34]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\HEMANT~1\AppData\Local\Temp/ipykernel_13752/487797088.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [35]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [36]:
import nltk

In [37]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [38]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [39]:
new_df['tags']=new_df['tags'].apply(stem)

C:\Users\HEMANT~1\AppData\Local\Temp/ipykernel_13752/3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [40]:
new_df['tags'][0]

"in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict samworthington zoesaldana sigourneyweav stephenlang michellerodriguez giovanniribisi joeldavidmoor cchpounder wesstudi lazalonso dileeprao mattgerald seananthonymoran jasonwhyt scottlawr kellykilgour jamespatrickpitt seanpatrickmurphi peterdillon kevindorman kelsonhenderson davidvanhorn jacobtomuri michaelblain-rozgay joncurri lukehawk woodyschultz petermensah soniaye jahnelcurfman ilramchoi kylawarren lisaroumain debrawilson chrismala taylorkibbi jodielandau julielamm cullenb.madden josephbradymadden frankietorr austinwilson sarawilson tamicawashington-mil lucybri nathanmeist gerryblair matthewchamberlain paulyat wraywilson jamesgaylyn melvinlenoclarkiii carvonfutrel brandonjelk micahmoch hanniyahmuhammad christophernolen christaoliv aprilmariethoma bravitaa.threatt colinbleasdal mikebodnar mattclayton nicoledionn jamieharrison allanhenri anthonyingrub ashleyjefferi deanknowsley josephmika-hunt terrynotari kaipantano loganpithy stuartpollock raja garethruck rhiansheehan t.j.storm jodietaylor aliciavela-bailey richardwhitesid nikiezambo julenerene stephene.rivkin rickcart christopherboy christopherboy malifinn jameshorn jamescameron jamescameron jamescameron jamescameron jamescameron andrewmenzi jillbrook margerysimkin kevinishioka dickbernstein shannonmil denniethorp janav deborahlynnscott jonlandau seanhaworth kimsinclair kimsinclair richardf.may laetakalogridi mayesc.rubeo maurofior scottherbertson woodyschultz lindadevetta lindadevetta richardbluck simonbright richardmartin stever.moor johnrefoua karlj.martin chilinglin ilramchoi stevenqual carlamey nickbassett jillcormack andymclaren terrynotari garrettwarren jonathanrothbart stefandech toddcherniawski mirandariv robertstromberg johnhard robertodeang mikesmithson alainlalann lucassalton janacetashjian stephenrosenbaum frankiekarena lisalovaa jonathanfawkn robertbavin anthonyalmaraz carolynm.fenton bethkoenigsberg sampag texkadonaga kimfoscato tammys.le dennycaira jameswaitku addisonteagu c.scottbak lukecaska davidchow jonathandy josephhiura rebeccajelli robertandrewjohnson mikestassi johnvillarino jeffreywisniewski cherylnardi marshallwinn gwendolynyateswhittl williamstein lulawashington chrisdelcont r.christopherwhit danlemmon timnielsen michaelmulholland thomasnittmann edsonwilliam christinecarr johnbruno davidemmerich christopherscarabosio jennifertev brigitteyork kenfisch iainhutton steveingram joycecox jennyfost christophermarino jimmilton cyndioch lucasputnam anthony'max'ivin johnknol ericsaindon waynest davidstinnett guywilliam stuartthorp gilescoburn markfellman scottspragu jeremyhollobon orlandomeuni taisuketanimura liliamishelacevedo alejandrom.hernandez marvinhal judyalley mikeperri andrewmorley sethengstrom ericoliv matsunesuzuki paultobin roxanegriffin arunram-mohan georgialockhart-adam thrainshadbolt bradalexand shadialmassizadeh simonclutterbuck graemedemmock adrianfernand mitchgat jerrykung andyloma sebastianmarino matthiasmenz sergeinevshupov philipperebour michaeltakarangi davidweitzberg benwhit minwindl cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d"

In [41]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

C:\Users\HEMANT~1\AppData\Local\Temp/ipykernel_13752/4224080999.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [42]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

In [43]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

In [44]:
vectors=cv.fit_transform(new_df['tags']).toarray()

In [45]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [46]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [47]:
cv.get_feature_names()

['000',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '18th',
 '1930',
 '1940',
 '1950',
 '1960',
 '1970',
 '1980',
 '19th',
 '19thcenturi',
 '20',
 '20th',
 '24',
 '30',
 '3d',
 '40',
 '50',
 '60',
 '70',
 'aaron',
 'aaroneckhart',
 'aaronseltz',
 'aaronwilliam',
 'aaronzigman',
 'aasifmandvi',
 'abandon',
 'abduct',
 'abigailbreslin',
 'abil',
 'abl',
 'abov',
 'abram',
 'abus',
 'academi',
 'accept',
 'access',
 'accid',
 'accident',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'achiev',
 'ackerman',
 'act',
 'action',
 'activ',
 'activist',
 'actor',
 'actress',
 'actual',
 'adam',
 'adambrodi',
 'adamdal',
 'adamgoldberg',
 'adamjenkin',
 'adamlefevr',
 'adammckay',
 'adammilosmalley',
 'adamsandl',
 'adamscott',
 'adamshankman',
 'adapt',
 'addict',
 'adewaleakinnuoye',
 'admir',
 'adolesc',
 'adopt',
 'adrianbiddl',
 'adrienbrodi',
 'adult',
 'adulteri',
 'advanc',
 'adventur',
 'adventure',
 'advertis',
 'advic',
 'affair',
 'affect',
 'afghanistan',
 'africa',
 'african',
 'aftercreditssting',
 'afterlif',
 'ag',
 'agbaj',
 'age',
 'agent',
 'ago',
 'agre',
 'aguilar',
 'ahead',
 'ai',
 'aid',
 'aidanquinn',
 'aim',
 'air',
 'airplan',
 'airport',
 'akivagoldsman',
 'al',
 'alanalda',
 'alanarkin',
 'alanb',
 'alancum',
 'aland',
 'alanmenken',
 'alanrickman',
 'alanrobertmurray',
 'alansilvestri',
 'alantudyk',
 'alaska',
 'albert',
 'albertbrook',
 'albertgass',
 'albertr',
 'albertwolski',
 'alcohol',
 'alecbaldwin',
 'alechammond',
 'alejandroamenábar',
 'alejandrogonzáleziñárritu',
 'alessandro',
 'alex',
 'alexanderpayn',
 'alexandredesplat',
 'alexapenavega',
 'alexgibson',
 'alexkendrick',
 'alexkurtzman',
 'alexrous',
 'alfonsocuarón',
 'alfredhitchcock',
 'alfredmolina',
 'alfrewoodard',
 'ali',
 'alic',
 'aliciastevenson',
 'alien',
 'alieninvas',
 'aliv',
 'alive',
 'allana',
 'allangraf',
 'allen',
 'allencovert',
 'allenhal',
 'alli',
 'allianc',
 'allisonjanney',
 'allisonjon',
 'allow',
 'alon',
 'alpacino',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'alysondeemoor',
 'amanda',
 'amandamackey',
 'amandapeet',
 'amandaseyfri',
 'amaz',
 'ambassador',
 'ambit',
 'ambiti',
 'ambush',
 'america',
 'american',
 'americanfootbal',
 'amico',
 'amnesia',
 'amp',
 'amus',
 'amyadam',
 'amypoehl',
 'amysmart',
 'anamariaquintana',
 'anastasn',
 'ancient',
 'anderson',
 'andi',
 'andiemacdowel',
 'andrew',
 'andrewa',
 'andrewadamson',
 'andrewcoop',
 'andrewdecristofaro',
 'andrewdunn',
 'andrewg',
 'andrewlaw',
 'andrewlazar',
 'andrewlesni',
 'andrewm',
 'andrewmenzi',
 'andrewneskoromni',
 'andrewniccol',
 'andrewstanton',
 'android',
 'andrzejbartkowiak',
 'andydick',
 'andygarcía',
 'andykaplan',
 'andymalcolm',
 'andynelson',
 'andyricht',
 'andysamberg',
 'andyserki',
 'angel',
 'angelabassett',
 'angeles',
 'angelinajoli',
 'angelo',
 'anger',
 'angerio',
 'angri',
 'ani',
 'anim',
 'anjelicahuston',
 'ann',
 'anna',
 'annab',
 'annabehlm',
 'annafari',
 'annakendrick',
 'annapaquin',
 'annapinnock',
 'annaran',
 'anndowd',
 'anne',
 'annefletch',
 'annehathaway',
 'annehech',
 'annekuljian',
 'annemccarthi',
 'annemoss',
 'annetteben',
 'anni',
 'anniepenn',
 'anniewel',
 'announc',
 'annroth',
 'annscibelli',
 'anntenggren',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'anthoni',
 'anthonyanderson',
 'anthonyb',
 'anthonybregman',
 'anthonydininno',
 'anthonyhopkin',
 'anthonyj',
 'anthonykataga',
 'anthonymacki',
 'anthonyminghella',
 'anthonyrizzo',
 'anti',
 'antihero',
 'antoni',
 'antonicoron',
 'antoniobandera',
 'antonyelchin',
 'anyon',
 'anyth',
 'apart',
 'apartment',
 'ape',
 'apocalyps',
 'apocalypt',
 'apon',
 'appar',
 'appear',
 'appoint',
 'approach',
 'april',
 'archaeologist',
 'architect',
 'arci',
 'area',
 'arena',
 'aris',
 'aristocrat',
 'arm',
 'armi',
 'armstrong',
 'army',
 'armyanbernstein',
 'arnold',
 'arnoldschwarzenegg',
 'arnonmilchan',
 'arrang',
 'arrest',
 'arriv',
 'art',
 'arthur',
 'arthurj',
 'arthurmax',
 'arthurschmidt',
 'artificialintellig',
 'artist',
 'artlinson',
 'ashley',
 'ashleyjudd',
 'ashtonkutch',
 'ask',
 'aspir',
 'assassin',
 'assault',
 'assign',
 'assist',
 'associ',
 'assum',
 'astronaut',
 'asylum',
 'ateah',
 'athlet',
 'atomegoyan',
 'attack',
 'attempt',
 'attend',
 'attent',
 'attorney',
 'attract',
 'audienc',
 'audit',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'auto',
 'aveng',
 'aviarad',
 'avilern',
 'avoid',
 'avykaufman',
 'await',
 'awaken',
 'award',
 'away',
 'babi',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'bad',
 'bail',
 'bailey',
 'bak',
 'balanc',
 'ball',
 'ballet',
 'band',
 'bank',
 'banker',
 'bar',
 'barbarabroccoli',
 'barbaraharri',
 'barbrastreisand',
 'bare',
 'bargain',
 'barn',
 'barney',
 'barri',
 'barrybernardi',
 'barrychusid',
 'barryh',
 'barrylevinson',
 'barrymendel',
 'barrypepp',
 'barrysonnenfeld',
 'bas',
 'base',
 'basebal',
 'basedoncomicbook',
 'basedonnovel',
 'basedonplay',
 'basedontrueev',
 'basedontruestori',
 'basedontvseri',
 'basedonvideogam',
 'basedonyoungadultnovel',
 'basement',
 'basiliwanyk',
 'basilpoledouri',
 'basketbal',
 'batman',
 'battl',
 'bazluhrmann',
 'beach',
 'bear',
 'beast',
 'beat',
 'beatrixarunapasztor',
 'beaubord',
 'beauflynn',
 'beauti',
 'becam',
 'becaus',
 'beckysullivan',
 'becom',
 'becominganadult',
 'bed',
 'befor',
 'befriend',
 'began',
 'begin',
 'behavior',
 'bel',
 'believ',
 'belong',
 'belov',
 'ben',
 'benaffleck',
 'benavent',
 'bend',
 'bendavi',
 'benedictcumberbatch',
 'benfost',
 'bengar',
 'beniciodeltoro',
 'benjaminbratt',
 'benjamínfernández',
 'benkingsley',
 'bennett',
 'benstil',
 'bent',
 'bentley',
 'benwaisbren',
 'berg',
 'berlin',
 'berndeiching',
 'berniemac',
 'bess',
 'best',
 'bestfriend',
 'bet',
 'bethgrant',
 'betray',
 'bettemidl',
 'better',
 'bibl',
 'big',
 'biggest',
 'biker',
 'billabbott',
 'billbernstein',
 'billcarraro',
 'billcobb',
 'billcorso',
 'billhad',
 'billi',
 'billionair',
 'billjohnson',
 'billmurray',
 'billnighi',
 'billnunn',
 'billo',
 'billpankow',
 'billpaxton',
 'billpop',
 'billpullman',
 'billybobthornton',
 'billyconnolli',
 'billycrudup',
 'billycryst',
 'billyhopkin',
 'billyweb',
 'billyzan',
 'biographi',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bissel',
 'bit',
 'bite',
 'bitter',
 'bizarr',
 'black',
 'blackmail',
 'blackpeopl',
 'blade',
 'blame',
 'blind',
 'bliss',
 'block',
 'blood',
 'bloodi',
 'bloodthirsti',
 'bloom',
 'blow',
 'blue',
 'board',
 'boat',
 'bob',
 'bobbadami',
 'bobbalaban',
 'bobbeem',
 'bobbi',
 'bobbycannaval',
 'bobbyfarrelli',
 'bobgunton',
 'bobhoskin',
 'bobkensing',
 'bobweinstein',
 'bobyari',
 'bodi',
 'body',
 'bodyguard',
 'bokeemwoodbin',
 'bomb',
 'bond',
 'bonniehunt',
 'bonnietimmermann',
 'book',
 'border',
 'bore',
 'born',
 'boss',
 'boston',
 'bound',
 'bounti',
 'bountyhunt',
 'bourn',
 'box',
 'boxer',
 'boy',
 'boyd',
 'boyfriend',
 'boys',
 'bradbird',
 'braddourif',
 'bradgarrett',
 'bradleycoop',
 'bradpitt',
 'bradsherman',
 'brain',
 'brandontrost',
 'brave',
 'braveri',
 'break',
 'breckinmey',
 'brendanfras',
 'brendangleeson',
 'brentspin',
 'brettratn',
 'brian',
 'brianaveri',
 'briancox',
 'briandennehi',
 'briandepalma',
 'briandoyle',
 'briangraz',
 'brianhel',
 'brianhelgeland',
 'brianj',
 'briann',
 'brianrichard',
 'briantaylor',
 'briantyl',
 'bride',
 'bridg',
 'brief',
 'brielarson',
 'brien',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'britishsecretservic',
 'brittanymurphi',
 'broadway',
 'broccoli',
 'broderickjohnson',
 'broke',
 'broken',
 'brook',
 'brooklyn',
 'broom',
 'brother',
 'brotherbrotherrelationship',
 'brothersisterrelationship',
 'brought',
 'brown',
 'brubak',
 'bruc',
 'bruce',
 'brucea',
 'bruceberman',
 'brucecampbel',
 'brucedern',
 'brucefowl',
 'brucegreen',
 'brucegreenwood',
 'brucemcgil',
 'brucesp',
 'brucewilli',
 'brutal',
 'bryan',
 'bryanbowen',
 'bryancranston',
 'bryansing',
 'bu',
 'bubasman',
 'buck',
 'buckley',
 'buddi',
 'build',
 'bulli',
 'bumbl',
 'buri',
 'burk',
 'burn',
 'burton',
 'burtreynold',
 'bush',
 'busi',
 'business',
 'businessman',
 'bust',
 'butl',
 'buy',
 'byrn',
 'cabin',
 'cabrera',
 'cal',
 'calebdeschanel',
 'california',
 'callumkeithrenni',
 'calvin',
 'came',
 'camera',
 'cameron',
 'cameroncrow',
 'camerondiaz',
 'camillefriend',
 'camp',
 'campaign',
 'campanelli',
 'campbel',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'cannib',
 'capabl',
 'capit',
 'captain',
 'captiv',
 'captur',
 'car',
 'caracciolojr',
 'carchas',
 'carcrash',
 'card',
 'care',
 'career',
 'caribbean',
 'carl',
 'carlagugino',
 'carlson',
 'carmen',
 'carola',
 'carolineaaron',
 'carolinegoodal',
 'carolkief',
 'carolspi',
 'carpent',
 'carrac',
 'carri',
 'carrie',
 'carriefish',
 'cart',
 'carter',
 'carterburwel',
 'caruso',
 'cary',
 'caryelw',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castl',
 'cat',
 'catch',
 'cateblanchett',
 'catehardman',
 'catherinehardwick',
 'catherineharp',
 'catherinekeen',
 'catherineo',
 'catherinezeta',
 'cathey',
 'cathol',
 'cathysandrich',
 'caught',
 'caus',
 'cave',
 'cedrictheentertain',
 'celebr',
 'celiad',
 'celiaimri',
 'celiaweston',
 'center',
 'central',
 'centuri',
 'century',
 'certain',
 'chadoman',
 'chain',
 'challeng',
 'champion',
 'championship',
 'chanc',
 'chancekelli',
 'chang',
 'channingtatum',
 'chao',
 'charact',
 'characters',
 'charg',
 'charl',
 'charlesd',
 'charlesdurn',
 'charlesmayn',
 'charlesroven',
 'charless',
 'charlesw',
 'charli',
 'charlie',
 'charliekaufman',
 'charliesheen',
 'charlizetheron',
 'charlotterampl',
 'charltonheston',
 'charm',
 'chase',
 'chavez',
 'chazzpalminteri',
 'cheat',
 'cheechmarin',
 'cheerlead',
 'chef',
 'chevychas',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabus',
 'childhood',
 'children',
 'chimcbrid',
 'china',
 'chines',
 'chip',
 'chiwetelejiofor',
 'chloëgracemoretz',
 'choic',
 'choos',
 'chosen',
 'chri',
 'chrisanderson',
 'chrisbend',
 'chrisbrown',
 'chrisburdon',
 'chriscolumbu',
 'chriscoop',
 'chriscornwel',
 'chriselli',
 'chrisevan',
 'chrishaarhoff',
 'chrishemsworth',
 'chrishogan',
 'chrisjenkin',
 'chrisl',
 'chrislebenzon',
 'chrismil',
 'chriso',
 'chrispin',
 'chrispratt',
 'chrisrock',
 'chrissand',
 'chrisseag',
 'chrissnyd',
 'christ',
 'christensen',
 'christian',
 'christianbal',
 'christianp',
 'christianslat',
 'christianwagn',
 'christinaappleg',
 'christinaricci',
 'christinebaranski',
 'christinewilson',
 'christma',
 'christmasparti',
 'christoph',
 'christophebeck',
 'christopherassel',
 'christopherboy',
 'christopherdoyl',
 'christophergreenburi',
 'christopherguest',
 'christopherle',
 'christopherlennertz',
 'christopherlloyd',
 'christophermcdonald',
 'christophermcquarri',
 'christophermil',
 'christophermintz',
 'christophernolan',
 'christopherplumm',
 'christophers',
 'christopherscarabosio',
 'christophert',
 'christopherwalken',
 'christopheryoung',
 'christophwaltz',
 'chrisweitz',
 'chronicl',
 'chu',
 'chuckduk',
 'chuckmichael',
 'church',
 'cia',
 'ciaránhind',
 'cillianmurphi',
 'cindycarr',
 'circu',
 'citi',
 'citizen',
 'city',
 'civil',
 'civilwar',
 'claim',
 'clair',
 'claireforlani',
 'clan',
 'clancybrown',
 'clark',
 'clarkgregg',
 'clash',
 'class',
 'classic',
 'classmat',
 'claudevandamm',
 'claytontownsend',
 'cleaduval',
 'clean',
 'clear',
 'clerk',
 'client',
 'cliffcurti',
 'cliffmartinez',
 'cliftoncollinsjr',
 'climb',
 'clinteastwood',
 'clinthoward',
 'clintmansel',
 'clinton',
 'cliveowen',
 'clock',
 'clone',
 'clorisleachman',
 'close',
 'closer',
 'club',
 'clue',
 'coach',
 'coast',
 'cocain',
 'code',
 'codycameron',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colehaus',
 'colinanderson',
 'colinfarrel',
 'colinfirth',
 'colinsalmon',
 'colinwilson',
 'collaps',
 'colleagu',
 'collect',
 'collector',
 'colleenatwood',
 'colleencamp',
 'colleg',
 'college',
 'collid',
 'collin',
 'colmfeor',
 'colonel',
 'coloni',
 'color',
 'coma',
 'combat',
 'combin',
 'come',
 'comedi',
 'comedian',
 'comedy',
 'comfort',
 'comic',
 'coming',
 'comingofag',
 'command',
 'commerci',
 'commit',
 'common',
 'commun',
 'compani',
 'companion',
 'company',
 'compet',
 'competit',
 'complet',
 'complex',
 'complic',
 'comput',
 'concert',
 'condit',
 'confid',
 'conflict',
 'confront',
 'confus',
 'connect',
 'connel',
 'connor',
 'conquer',
 'conradbuffiv',
 'conradvernon',
 'consequences',
 'consid',
 'conspiraci',
 'construct',
 'consum',
 'contact',
 'contain',
 'contest',
 'continu',
 'contract',
 'control',
 'controversi',
 'convent',
 'convict',
 'convinc',
 'cook',
 'cool',
 'coop',
 'cooper',
 'cop',
 'cope',
 'coreenmayr',
 'coreyburton',
 'corner',
 'corpor',
 'corps',
 'corrupt',
 'cosmaspaulbolgerjr',
 'cost',
 'costa',
 'costanzo',
 'costum',
 'count',
 'countri',
 'country',
 'countrysid',
 'coupl',
 'couple',
 'courag',
 'cours',
 'court',
 'courtcas',
 'cousin',
 'cover',
 'covert',
 'cowardli',
 ...]

In [48]:
ps.stem('dance')

'danc'

In [49]:
stem("In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction SamWorthington ZoeSaldana SigourneyWeaver StephenLang MichelleRodriguez GiovanniRibisi JoelDavidMoore CCHPounder WesStudi LazAlonso DileepRao MattGerald SeanAnthonyMoran JasonWhyte ScottLawrence KellyKilgour JamesPatrickPitt SeanPatrickMurphy PeterDillon KevinDorman KelsonHenderson DavidVanHorn JacobTomuri MichaelBlain-Rozgay JonCurry LukeHawker WoodySchultz PeterMensah SoniaYee JahnelCurfman IlramChoi KylaWarren LisaRoumain DebraWilson ChrisMala TaylorKibby JodieLandau JulieLamm CullenB.Madden JosephBradyMadden FrankieTorres AustinWilson SaraWilson TamicaWashington-Miller LucyBriant NathanMeister GerryBlair MatthewChamberlain PaulYates WrayWilson JamesGaylyn MelvinLenoClarkIII CarvonFutrell BrandonJelkes MicahMoch HanniyahMuhammad ChristopherNolen ChristaOliver AprilMarieThomas BravitaA.Threatt ColinBleasdale MikeBodnar MattClayton NicoleDionne JamieHarrison AllanHenry AnthonyIngruber AshleyJeffery DeanKnowsley JosephMika-Hunt TerryNotary KaiPantano LoganPithyou StuartPollock Raja GarethRuck RhianSheehan T.J.Storm JodieTaylor AliciaVela-Bailey RichardWhiteside NikieZambo JuleneRenee StephenE.Rivkin RickCarter ChristopherBoyes ChristopherBoyes MaliFinn JamesHorner JamesCameron JamesCameron JamesCameron JamesCameron JamesCameron AndrewMenzies JillBrooks MargerySimkin KevinIshioka DickBernstein ShannonMills DennieThorpe JanaVance DeborahLynnScott JonLandau SeanHaworth KimSinclair KimSinclair RichardF.Mays LaetaKalogridis MayesC.Rubeo MauroFiore ScottHerbertson WoodySchultz LindaDeVetta LindaDeVetta RichardBluck SimonBright RichardMartin SteveR.Moore JohnRefoua KarlJ.Martin ChilingLin IlramChoi StevenQuale CarlaMeyer NickBassett JillCormack AndyMcLaren TerryNotary GarrettWarren JonathanRothbart StefanDechant ToddCherniawsky MirandaRivers RobertStromberg JohnHarding RobertoDeAngelis MikeSmithson AlainLalanne LucasSalton JanaceTashjian StephenRosenbaum FrankieKarena LisaLovaas JonathanFawkner RobertBavin AnthonyAlmaraz CarolynM.Fenton BethKoenigsberg SamPage TexKadonaga KimFoscato TammyS.Lee DennyCaira JamesWaitkus AddisonTeague C.ScottBaker LukeCaska DavidChow JonathanDyer JosephHiura RebeccaJellie RobertAndrewJohnson MikeStassi JohnVillarino JeffreyWisniewski CherylNardi MarshallWinn GwendolynYatesWhittle WilliamStein LulaWashington ChrisDelConte R.ChristopherWhite DanLemmon TimNielsen MichaelMulholland ThomasNittmann EdsonWilliams ChristineCarr JohnBruno DavidEmmerichs ChristopherScarabosio JenniferTeves BrigitteYorke KenFischer IainHutton SteveIngram JoyceCox JennyFoster ChristopherMarino JimMilton CyndiOchs LucasPutnam Anthony'Max'Ivins JohnKnoll EricSaindon WayneStables DavidStinnett GuyWilliams StuartThorp GilesCoburn MarkFellman ScottSprague JeremyHollobon OrlandoMeunier TaisukeTanimura LiliaMishelAcevedo AlejandroM.Hernandez MarvinHall JudyAlley MikePerry AndrewMorley SethEngstrom EricOliver MatsuneSuzuki PaulTobin RoxaneGriffin ArunRam-Mohan GeorgiaLockhart-Adams ThrainShadbolt BradAlexander ShadiAlmassizadeh SimonClutterbuck GraemeDemmocks AdrianFernandes MitchGates JerryKung AndyLomas SebastianMarino MatthiasMenz SergeiNevshupov PhilippeRebours MichaelTakarangi DavidWeitzberg BenWhite MinWindle cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d")

"in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict samworthington zoesaldana sigourneyweav stephenlang michellerodriguez giovanniribisi joeldavidmoor cchpounder wesstudi lazalonso dileeprao mattgerald seananthonymoran jasonwhyt scottlawr kellykilgour jamespatrickpitt seanpatrickmurphi peterdillon kevindorman kelsonhenderson davidvanhorn jacobtomuri michaelblain-rozgay joncurri lukehawk woodyschultz petermensah soniaye jahnelcurfman ilramchoi kylawarren lisaroumain debrawilson chrismala taylorkibbi jodielandau julielamm cullenb.madden josephbradymadden frankietorr austinwilson sarawilson tamicawashington-mil lucybri nathanmeist gerryblair matthewchamberlain paulyat wraywilson jamesgaylyn melvinlenoclarkiii carvonfutrel brandonjelk micahmoch hanniyahmuhammad christophernolen christaoliv aprilmariethoma bravitaa.threatt colinbleasdal mikebodnar mattclayton nicoledionn jamieharrison allanhenri anthonyingrub ashleyjefferi deanknowsley josephmika-hunt terrynotari kaipantano loganpithy stuartpollock raja garethruck rhiansheehan t.j.storm jodietaylor aliciavela-bailey richardwhitesid nikiezambo julenerene stephene.rivkin rickcart christopherboy christopherboy malifinn jameshorn jamescameron jamescameron jamescameron jamescameron jamescameron andrewmenzi jillbrook margerysimkin kevinishioka dickbernstein shannonmil denniethorp janav deborahlynnscott jonlandau seanhaworth kimsinclair kimsinclair richardf.may laetakalogridi mayesc.rubeo maurofior scottherbertson woodyschultz lindadevetta lindadevetta richardbluck simonbright richardmartin stever.moor johnrefoua karlj.martin chilinglin ilramchoi stevenqual carlamey nickbassett jillcormack andymclaren terrynotari garrettwarren jonathanrothbart stefandech toddcherniawski mirandariv robertstromberg johnhard robertodeang mikesmithson alainlalann lucassalton janacetashjian stephenrosenbaum frankiekarena lisalovaa jonathanfawkn robertbavin anthonyalmaraz carolynm.fenton bethkoenigsberg sampag texkadonaga kimfoscato tammys.le dennycaira jameswaitku addisonteagu c.scottbak lukecaska davidchow jonathandy josephhiura rebeccajelli robertandrewjohnson mikestassi johnvillarino jeffreywisniewski cherylnardi marshallwinn gwendolynyateswhittl williamstein lulawashington chrisdelcont r.christopherwhit danlemmon timnielsen michaelmulholland thomasnittmann edsonwilliam christinecarr johnbruno davidemmerich christopherscarabosio jennifertev brigitteyork kenfisch iainhutton steveingram joycecox jennyfost christophermarino jimmilton cyndioch lucasputnam anthony'max'ivin johnknol ericsaindon waynest davidstinnett guywilliam stuartthorp gilescoburn markfellman scottspragu jeremyhollobon orlandomeuni taisuketanimura liliamishelacevedo alejandrom.hernandez marvinhal judyalley mikeperri andrewmorley sethengstrom ericoliv matsunesuzuki paultobin roxanegriffin arunram-mohan georgialockhart-adam thrainshadbolt bradalexand shadialmassizadeh simonclutterbuck graemedemmock adrianfernand mitchgat jerrykung andyloma sebastianmarino matthiasmenz sergeinevshupov philipperebour michaeltakarangi davidweitzberg benwhit minwindl cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d"

In [50]:
from sklearn.metrics.pairwise import cosine_similarity

In [51]:
similarity=cosine_similarity(vectors)

In [52]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(25, 0.27643789618603526),
 (2409, 0.27574350900541733),
 (279, 0.21320071635561044),
 (282, 0.20124611797498107),
 (539, 0.1876388374866284)]

In [53]:
def recommend(movie):
    movie_index=new_df[new_df['title']==movie].index[0]
    distances=similarity[movie_index]
    movies_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [54]:
recommend('Batman Begins')

The Dark Knight
The Dark Knight Rises
Batman
Batman v Superman: Dawn of Justice
Batman

In [55]:
new_df.iloc[2409].title

'Aliens'

In [56]:
import pickle

In [57]:
pickle.dump(new_df,open('movies.pkl','wb'))

In [58]:
new_df['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

In [59]:
pickle.dump(new_df.to_dict(),open('movies_dict.pkl','wb'))

In [60]:
pickle.dump(similarity,open('similarity.pkl','wb'))